<?php
	namespace frontend\components;
	use yii\base\Widget;
	use yii\helpers\Html;

	class RctReplyWidget extends Widget{

		public $recentComments;

		public function init()
		{
			parent::init(); // TODO: Change the autogenerated stub
		}
		public function run()
		{
//			parent::run(); // TODO: Change the autogenerated stub
			$commentString='';
			foreach ($this->recentComments as $comment) {
				$commentString.='
							<div class="post">
							    <div class="title">
							        <p style="color: #777777;font-style: italic;">'.nl2br($comment->content).'</p>
							        <p style="font-size: 8pt;color: blue;">
							            << <a href="'.$comment->post->url.'">'.Html::encode($comment->post->title).'</a> >>
							        </p>
							        <hr>
							    </div>
							</div>
				';
			}
			return $commentString;
		}
	}